name: ulpon-dev

services:
  mysql:
    image: mysql:8.4.9
    container_name: mysql
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # root 密码
      MYSQL_ROOT_PASSWORD: admin123
      # 初始化数据库(后续的初始化sql会在这个库执行)
      MYSQL_DATABASE: db_ulpon
    ports:
      - "3306:3306"
    volumes:
      - ../sql/:/docker-entrypoint-initdb.d
      - ../:/share
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true

  redis:
    image: redis:8.6.3
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ../:/share
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    command:
      - redis-server
      - --requirepass
      - admin123
    privileged: true

  minio:
    # pgsty 开源社区 fork 重新维护的最新版 minio
    image: pgsty/minio:RELEASE.2026-04-17T00-00-00Z
    container_name: minio
    ports:
      # api 端口
      - "9000:9000"
      # 控制台端口
      - "9001:9001"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # 管理后台用户名
      MINIO_ROOT_USER: admin
      # 管理后台密码，最小8个字符
      MINIO_ROOT_PASSWORD: admin123
      # https需要指定域名
      #MINIO_SERVER_URL: "https://xxx.com:9000"
      #MINIO_BROWSER_REDIRECT_URL: "https://xxx.com:9001"
      # 开启压缩 on 开启 off 关闭
      MINIO_COMPRESS: "off"
      # 扩展名 .pdf,.doc 为空 所有类型均压缩
      MINIO_COMPRESS_EXTENSIONS: ""
      # mime 类型 application/pdf 为空 所有类型均压缩
      MINIO_COMPRESS_MIME_TYPES: ""
    volumes:
      - ../:/share
    command: server --address ':9000' --console-address ':9001' /data  # 指定容器中的目录 /data
    privileged: true
