<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.dromara</groupId>
    <artifactId>ruoyi-module-bom</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <properties>
        <revision>6.0.0</revision>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- 系统模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-system</artifactId>
                <version>${revision}</version>
            </dependency>

            <!-- 调度任务模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-job</artifactId>
                <version>${revision}</version>
            </dependency>

            <!-- AI业务模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-ai</artifactId>
                <version>${revision}</version>
            </dependency>

            <!-- 代码生成模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-gen</artifactId>
                <version>${revision}</version>
            </dependency>

            <!-- demo模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-demo</artifactId>
                <version>${revision}</version>
            </dependency>

            <!--  工作流模块  -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-workflow</artifactId>
                <version>${revision}</version>
            </dependency>

            <!--  api模块  -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-api</artifactId>
                <version>${revision}</version>
            </dependency>

            <!-- ai模块 -->
            <dependency>
                <groupId>com.ulpon</groupId>
                <artifactId>ulpon-ai</artifactId>
                <version>${revision}</version>
            </dependency>

            <!-- geo模块 -->
            <dependency>
                <groupId>com.ulpon</groupId>
                <artifactId>ulpon-geo</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
